language: php

php:
    - 7.2
    - 7.3
    - 7.4

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

install:
    - |
      if [ "$(phpenv version-name)" == 7.4 ]; then
          sed -e 's#^\s*\$this->assertInternalType(.array., \$arrayOf);$#$this->assertIsArray($arrayOf);#' -i tests/ContainerTest.php
          travis_retry composer require "phpunit/phpunit:^9.0"
      fi
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
