language: php

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

install:
    - |
        # Instal PHPUnit v9 on PHP 8
        if [ "${TRAVIS_PHP_VERSION}" == nightly ]; then
            travis_retry composer require --no-interaction --prefer-dist --dev --ignore-platform-reqs "phpunit/phpunit:^9.3"
        else
            travis_retry composer install --no-interaction --prefer-dist
        fi

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
